<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>drpdown_Accepted_Status</name>
   <tag></tag>
   <elementGuidId>21aa6341-61b4-4d6a-a74a-1d293a0d8f10</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[text()='Status']//..//div[@role=&quot;listbox&quot;]//lightning-base-combobox-item[@data-value=&quot;Accepted&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
